# Generated by Django 5.0.4 on 2026-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
