# Generated by Django 5.0.4 on 2026-05-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_booking_bookingevent_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='districts',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='vendors.district'),
        ),
    ]
