# Generated by Django 5.0.4 on 2026-05-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_vendor_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='joining_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
