server {
    listen 80;
    server_name 52.204.212.158; # Replace this later if your IP changes or you get a domain

    client_max_body_size 20M;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Handle static files (Django WhiteNoise usually handles this, 
    # but Nginx is faster for images)
    location /static/ {
        alias /home/ubuntu/WedConnect/Backend/staticfiles/;
    }

    location /media/ {
        alias /home/ubuntu/WedConnect/Backend/mediafiles/;
    }
}
